apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-runner-cluster-admin
subjects:
  - kind: ServiceAccount
    name: mi-runners-gha-rs-no-permission
    namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io